<?php
/*
 This file was automatically generated by calgamo framework.

 builder version: %builder_ver%
 hash: %config_hash%
 build at: %build_date%
*/
require_once '%vendor_dir%/autoload.php';

use Calgamo\Util\ExceptionHelper;
use Calgamo\Router\Router;
use Calgamo\Router\Node\RootNode;
use Calgamo\Router\Exception\SerializedDataCorruptedException;

// return bootstrap callback
return function(Router $router){
    
    $root = unserialize('%serialized%');

    if (!($root instanceof RootNode)){
        ExceptionHelper::throw( new SerializedDataCorruptedException(__FILE__) );
    }

    $router->replaceRoot($root);

// return config hash
    return '%config_hash%';
};